grade/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('adminpage/', views.admin, name='adminpage'),

    ##### ADMIN #####
    path('adminpage/teachers', views.TeacherListView.as_view(), name='teacher-list'),
    path('adminpage/students', views.StudentListView.as_view(),
         name='admin-student-list'),
    path('adminpage/students/<int:pk>',
         views.StudentInformationView.as_view(), name='student-info'),
    path('adminpage/student-subjects/<int:pk>', views.StudentSubjectListView.as_view(),
         name='student-subjects'),
    path('adminpage/student-subjects/form/<int:pk>',
         views.StudentSubjectForm.as_view(), name='student-subjects-form'),


    ##### TEACHER #####
    # path('teacher/', views.teacher, name='teacher'),
    path('teacher', views.HomeStudentList.as_view(), name='teacher'),
    path('teacher/subjects/', views.TeacherSubjectListView.as_view(),
         name='teacher-subjects'),
    path('teacher/subjects/student-list/<int:subject_name_id>/<str:year_taken>/',
         views.StudentList.as_view(), name='student-list'),
    path('<pk>/update', views.GradeUpdateView.as_view(), name='grade-update'),
    path('password/', views.PasswordChangeView.as_view(
        template_name='register/change_password.html'), name='password-change'),
    path('password_success/', views.password_success, name='password_success'),


    ##### STUDENT #####
    path('student/', views.student, name='student'),
    path('<int:pk>', views.StudentSubjects.as_view(), name='student-grade'),
]

grade_viewer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from users import views as user_views

# media
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grade.urls')),

    path('logout/', auth_views.LogoutView.as_view(template_name='register/logout.html'), name='logout'),

    # profile
    path('profile/', user_views.profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

grade/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_extensions.db.fields import AutoSlugField
from django.core.validators import MinValueValidator, MaxValueValidator
from grade_viewer import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class User(AbstractUser):
    is_admin = models.BooleanField('Is admin', default=False)
    is_teacher = models.BooleanField('Is teacher', default=False)
    is_student = models.BooleanField('Is student', default=False)


class Course(models.Model):
    course = models.CharField(max_length=225, blank=True, null=True)

    def __str__(self):
        return self.course


class Student(models.Model):

    GENDER = (
        ('1', 'Male'),
        ('2', 'Female')
    )

    STATUS = (
        ('1', 'Ongoing'),
        ('2', 'On Probition'),
        ('3', 'NA')
    )

    name = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    id_number = models.IntegerField(blank=True, null=True)
    gender = models.CharField(
        max_length=10, choices=GENDER, blank=True, null=True)
    date_of_birth = models.CharField(max_length=20, blank=True, null=True)
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, blank=True, null=True)
    year_level = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS, default='3')

    def __str__(self):
        return str(self.name)


class Teacher(models.Model):
    name = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return str(self.name)


class SchoolSubject(models.Model):
    subject_name = models.CharField(max_length=250)

    def __str__(self):
        return self.subject_name


class Subject(models.Model):

    SEMESTER_CHOICES = (
        ('1st', '1st Sem'),
        ('2nd', '2nd Sem')
    )
    REMARKS = (
        ('1', 'Passed'),
        ('2', 'Failed'),
        ('3', 'No Grade'),
        ('4', 'Incomplete')
    )
    instructor = models.ForeignKey(
        Teacher, on_delete=models.CASCADE, unique=False)
    name = models.ForeignKey(
        Student, on_delete=models.CASCADE)
    year_taken = models.CharField(max_length=225)
    semester = models.CharField(
        max_length=10, choices=SEMESTER_CHOICES, default='1st')
    # subject_name = models.ForeignKey(TeacherSubject, on_delete=models.CASCADE)
    subject_name = models.ForeignKey(
        SchoolSubject, on_delete=models.CASCADE, unique=False)
    grade = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True, validators=[
                                MinValueValidator(0.00), MaxValueValidator(5.00)])
    remarks = models.CharField(max_length=10, choices=REMARKS, default='3')
    slug = AutoSlugField(populate_from=['subject_name'], max_length=250)

    def __str__(self):
        return str(self.subject_name)

    class Meta:
        ordering = ['-year_taken', '-semester']


@receiver(post_save, sender=User)
def save_user(sender, instance, created, **kwargs):
    if created:
        if instance.is_student:
            Student.objects.create(name=instance)
        elif instance.is_teacher:
            Teacher.objects.create(name=instance)
    # elif instance.is_student and instance.is_teacher:
    #     Student.objects.create(name=instance)
    #     Teacher.objects.create(name=instance)

grade/views.py
from typing import List
from django.shortcuts import render, redirect, get_list_or_404
from django.urls.base import reverse
from .forms import SignUpForm, LoginForm, PasswordChangingForm, StudentInformationForm, StudentSubjectForm
from django.contrib.auth import authenticate, login
from django.views.generic import ListView
from .models import Student, Subject, Teacher, User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView, UpdateView, CreateView
from .forms import UpdateGradeForm
from django.urls import reverse_lazy
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
# Create your views here.


def index(request):
    return render(request, 'index.html')


def register(request):
    msg = None
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            msg = 'user created'
            return redirect('login_view')
        else:
            msg = 'form is not valid'
    else:
        form = SignUpForm()
    return render(request, 'register/register.html', {'form': form, 'msg': msg})


def login_view(request):
    form = LoginForm(request.POST or None)
    msg = None
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.is_admin:
                login(request, user)
                return redirect('adminpage')
            elif user is not None and user.is_student:
                login(request, user)
                return redirect('student-grade', pk=user.pk)
            elif user is not None and user.is_teacher:
                login(request, user)
                return redirect('teacher')
            else:
                msg = 'invalid credentials'
        else:
            msg = 'error validating form'
    return render(request, 'register/login.html', {'form': form, 'msg': msg})


##### ADMIN #####

def admin(request):
    return render(request, 'grade/admin.html')


class TeacherListView(ListView):
    model = Teacher
    template_name = 'grade/teacher_list.html'
    # context_object_name = 'teachers'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['teachers'] = Teacher.objects.all()
        return context


class StudentListView(ListView):
    model = Student
    template_name = 'grade/student_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = Student.objects.all()
        return context


class StudentInformationView(LoginRequiredMixin, UpdateView):
    model = Student
    template_name = 'grade/student_form.html'
    form_class = StudentInformationForm

    def get_success_url(self):
        return reverse_lazy('admin-student-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student'] = Student.objects.get(pk=self.kwargs.get('pk'))
        return context


class StudentSubjectListView(LoginRequiredMixin, ListView):
    model = Subject
    template_name = 'grade/student_subjects.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subjects'] = Subject.objects.filter(name=self.kwargs['pk'])
        context['student_subjects_url'] = Student.objects.get(
            pk=self.kwargs.get('pk'))
        # print(context['student_subjects_url'].pk)
        return context


class StudentSubjectForm(LoginRequiredMixin, CreateView):
    # model = Subject
    template_name = 'grade/subject_form.html'
    form_class = StudentSubjectForm

    def get_success_url(self):
        pk = self.object.pk
        qs = Subject.objects.get(pk=pk)
        student = qs.name.pk
        return reverse_lazy('student-subjects', kwargs={'pk': student})
        # return reverse_lazy('student-subjects', args={self.object.pk})

    # def get_initial(self):
    #     initial = super(StudentSubjectForm, self).get_initial()
    #     initial.update({'name': self.kwargs.get('pk')})
    #     print(self.kwargs.get('pk'))
    #     return initial

    def get_initial(self):
        return {'name': self.kwargs.get('pk')}

    # def form_valid(self, form):
    #     form.instance.name = Subject.objects.get(name=self.kwargs['pk'])
    #     print(self.kwargs['pk'])
    #     return super(StudentSubjectForm, self).form_valid(form)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['student_subjects'] = Subject.objects.get(
    #         name=self.kwargs.get('pk'))
    #     print(context)
    #     return context


##### STUDENT #####


def student(request):
    return render(request, 'student/student.html')


class StudentSubjects(ListView):
    model = Subject
    template_name = 'student/student_grade.html'
    context_object_name = 'student'

    def get_queryset(self, *args, **kwargs):
        names = get_list_or_404(
            Student, pk=self.kwargs.get('pk'))

        if 'school_year' in self.request.GET:
            school_year = self.request.GET['school_year']
            return Subject.objects.filter(name=names[0], year_taken=school_year)

        sub = Subject.objects.filter(name=names[0])
        return sub

    def get_context_data(self, **kwargs):
        names = get_list_or_404(
            Student, pk=self.kwargs.get('pk'))
        a = []
        b = []
        context = super().get_context_data(**kwargs)
        context['id_number'] = Student.objects.filter(
            pk=self.kwargs.get('id_number'))

        context['year'] = Subject.objects.filter(name=names[0])
        for i in context['year']:
            a.append(i.year_taken)
        # print(a)
        for i in a:
            if i not in b:
                b.append(i)
        # print(b)
        # context['years'] = Subject.objects.filter(year_taken=b[0])
        # print(b)

        # context['years'] = Subject.objects.all().order_by('year_taken')
        context['years'] = b

        context['information'] = Student.objects.filter(
            pk=self.request.user.pk)

        return context


##### TEACHER #####


# def teacher(request):
#     return render(request, 'teacher/teacher.html')


class TeacherSubjectListView(LoginRequiredMixin, ListView):
    model = Subject
    template_name = 'teacher/teacher_subjects.html'
    context_object_name = 'teacher_subject'
    # slug_field = 'slug'

    # def get_queryset(self):
    #     return get_object_or_404(Subject, self.get_object())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['teach_sub'] = Subject.objects.filter(
        #     instructor=self.request.user)
        # a = get_object_or_404(Subject, subject_name=self.kwargs.get('id'))
        # a = Subject.objects.filter(instructor=self.request.user.id, year_taken='2019-2020').values(
        #     'subject_name').annotate(Count('name')).order_by()
        # print(a)
        context['teach_sub'] = Subject.objects.filter(
            instructor_id=self.request.user.id).values('subject_name__subject_name', 'subject_name_id', 'year_taken', 'subject_name').annotate(Count('name')).order_by("-year_taken").distinct()

        # print(context)
        return context


class StudentList(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = 'student_list'
    template_name = 'teacher/student_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # a = Subject.objects.values_list('subject_name', flat=True).distinct()
        # print(a)

        context['students_enrolled'] = Subject.objects.filter(
            instructor=self.request.user.id, subject_name=self.kwargs['subject_name_id'], year_taken=self.kwargs['year_taken'])
        context['title'] = context['students_enrolled'][0]
        # print(context['students_enrolled'][0])

        male = 0
        female = 0
        passed = 0
        failed = 0
        inc = 0

        gender = Subject.objects.filter(instructor=self.request.user.id,
                                        subject_name=self.kwargs['subject_name_id'], year_taken=self.kwargs['year_taken']).values('name__gender')
        for key, value in enumerate(gender):
            if value['name__gender'] == '1':
                male += 1
            else:
                female += 1

        context['male'] = male
        context['female'] = female

        grade = Subject.objects.filter(instructor=self.request.user.id,
                                       subject_name=self.kwargs['subject_name_id'], year_taken=self.kwargs['year_taken']).values('remarks')

        for key, value in enumerate(grade):
            if value['remarks'] == '1':
                passed += 1
            elif value['remarks'] == '2':
                failed += 1
            else:
                inc += 1

        context['passed'] = passed
        context['failed'] = failed
        context['inc'] = inc

        return context


class GradeUpdateView(LoginRequiredMixin, UpdateView):
    model = Subject
    # template_name = 'teacher/modal.html'
    template_name = 'teacher/update_grade.html'
    # fields = ['grade']
    # success_url = '/'
    form_class = UpdateGradeForm

    def get_success_url(self):
        subject = self.object.subject_name
        year = self.object.year_taken
        return reverse_lazy('student-list', kwargs={"subject_name_id": subject.id, "year_taken": year})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student'] = Subject.objects.get(

grade/templates/student/navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  
  {% if request.user.is_student %}
    <a class="navbar-brand" href="{% url 'student-grade' user.pk %}">Online Grading</a>
  {% elif request.user.is_teacher%}
    <a class="navbar-brand" href="{% url 'teacher' %}">Online Grading</a>
  {% else %}
    <a class="navbar-brand" href="{% url 'adminpage' %}">Online Grading</a>
  {% endif %}
      
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      {% comment %} <li class="nav-item active">
        <a class="nav-link" href="{% url 'teacher-subjects' %}">Home <span class="sr-only">(current)</span></a>
      </li> {% endcomment %}
      {% comment %} <li class="nav-item">
        <a class="nav-link" href="{% url 'teacher-subjects' %}">Subjects</a>
      </li> {% endcomment %}

      
      {% if request.user.is_student %}
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.first_name}} {{user.last_name}}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'password-change' %}">Change Password</a>
            <a class="dropdown-item" href="{%url 'logout'%}">Logout</a>
          </div>
        </div>
      {% elif request.user.is_teacher %}
        <a class="nav-link" href="{% url 'teacher-subjects' %}">My Subjects</a>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.first_name}} {{user.last_name}}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'password-change' %}">Change Password</a>
            <a class="dropdown-item" href="{%url 'logout'%}">Logout</a>
          </div>
        </div>
      {% else %}
        {% comment %} <a class="nav-link" href="{% url 'teacher-subjects' %}">My Subjects</a> {% endcomment %}
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.first_name}} {{user.last_name}}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'password-change' %}">Change Password</a>
            <a class="dropdown-item" href="{%url 'logout'%}">Logout</a>
          </div>
        </div>
      {% endif %}
        

      

    </ul>

    {% comment %} <div class="form-inline my-2 my-lg-0">
      <a class="nav-item nav-link" style="color:silver" href="{%url 'logout'%}">Logout</a>

    </div> {% endcomment %}

    

</nav>

grade/templates/student/student.html
{% extends 'grade/base.html' %}

{% block contents %}
{% include 'student/navbar.html' %}

    <h1> hello {{ user.username }} your role is student</h1>
    <a href="{% url 'logout' %}">Logout</a>
    <a href="{% url 'student-grade' user.pk %}">Grades</a>
    

{% endblock contents %}

grade/templates/student/student_grade.html
{% extends 'grade/base.html' %}
{% load static %}

{% block contents %}
{% comment %} {% include 'student/navbar.html' %} {% endcomment %}

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <div class="sidebar-header">
                    {% if request.user.is_student %}
                        <a class="navbar-brand" href="{% url 'student-grade' user.pk %}">Online Grading</a>
                    {% elif request.user.is_teacher%}
                        <a class="navbar-brand" href="{% url 'teacher' %}">Online Grading</a>
                    {% else %}
                        <a class="navbar-brand" href="{% url 'adminpage' %}">Online Grading</a>
                    {% endif %}
                </div>
            </div>

            <ul class="list-unstyled components">
                <p>{{user.first_name}} {{user.last_name}}</p>
                <li>
                    <a href="{% url 'student-grade' user.pk %}">Home</a>
                </li>
                {% comment %} <li>
                    <a href="{% url 'teacher-subjects' %}">My Subjects</a>
                </li> {% endcomment %}
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Account</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'profile' %}">Edit Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'password-change' %}">Change Password</a>
                        </li>
                        {% comment %} <li>
                            <a href="#">Home 3</a>
                        </li> {% endcomment %}
                    </ul>
                </li>
                 <li>
                    <a href="{%url 'logout'%}">Logout</a>
                </li>
                {% comment %} <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Portfolio</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li> {% endcomment %}
            </ul>

            <ul class="list-unstyled CTAs">
                {% comment %} <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li> {% endcomment %}
                <footer class="text-center">&copy; JC Escala 2021 </footer>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    {% comment %} <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                        </ul>
                    </div> {% endcomment %}
                </div>
            </nav>

            <div class="container">

        <div class="about-card mb-3 mt-3" id="about-card">
            {% comment %} <h3 id="about">About Me</h3> {% endcomment %}
            {% comment %} <img class="rounded-circle account-img" id="student-image" src="{{ user.profile.image.url }}" width="90" height="90"> {% endcomment %}
            <div class="row">

                <div class="col-md-2 mt-3 text-center">
                    <img class="rounded-circle account-img" id="student-image" src="{{ user.profile.image.url }}" width="90" height="90">
                    {% comment %} {% if user.profile.image %}
                        <img class="rounded-circle account-img" id="student-image" src="{{ user.profile.image.url }}" width="90" height="90">
                    {% else %}
                        <img class="rounded-circle account-img" id="student-image" src="{% static 'images/default.jpg' %}" width="90" height="90">
                    {% endif %} {% endcomment %}
                        
                </div>
                
                <div class="col-md mt-3">
                    <h6><span id="student-name">Name:</span> <span id="student-name-info">{{user.first_name}} {{user.last_name}}</span></h6>
                    {% for info in information %}
                        <h6><span id="student-gender">Gender:</span> <span id="student-gender-info">{{info.get_gender_display}}</span></h6>
                        <h6><span id="student-birth">Date of Birth:</span> <span id="student-birth-info">{{info.date_of_birth}}</span></h6>
                    {% endfor %}

                </div>

                <div class="col-md mb-3 mt-3">    
                    {% for info in information %}
                        <h6><span id="student-course">Course:</span> <span id="student-course-info">{{info.course}}</span></h6>
                        <h6><span id="student-year">Year Level:</span> <span id="student-year-info">{{info.year_level}}</span></h6>
                        <h6><span id="student-status">Status:</span> <span id="student-status-info">{{info.get_status_display}}</span></h6>
                    {% endfor %}

                </div>

            </div>
        </div>
        
        <div class="col-md border" id="grade-card">
            <form id="dropdown_menu_form">
                <select class="btn" name="school_year" form="dropdown_menu_form" style="border-color:green">
                    <option disabled="true" selected>Select year</option>
                    {% for year in years %}
                        <option value="{{year}}">{{year}}</option>        
                    {% endfor %}
                </select>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Filter</button>
            </form>
            {% regroup student by year_taken as students %}
            {% for year_taken in students %}
                <div class="col-md text-center mt-3 table-responsive" style="margin:auto"><strong>School Year {{year_taken.grouper}}</strong></div>
                
                {% regroup year_taken.list by semester as sem %}
                {% for semm in sem %}
                    <strong>{{semm.grouper}} Semester</strong>

                

                    <table class="table table-striped table-hover table-bordered" width="100%">
                        <thead>
                            <tr>
                                <th scope="row">Subjects</th>
                                <th scope="row">Grade</th>
                                <th scope="row">Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for subject in semm.list %}
                                <tr>
                                    
                                    {% if subject.grade == 5.00 %}
                                        <td class="table-danger">{{subject.subject_name}}</td>
                                        <td class="table-danger">{{subject.grade}}</td>
                                        <td class="table-danger">{{subject.get_remarks_display}}</td>

                                    {% else %}
                                        <td>{{subject.subject_name}}</td>
                                        <td>{{subject.grade}}</td>
                                        <td>{{subject.get_remarks_display}}</td>
                                    {% endif %}
                                
                                </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                {% endfor %}
            {% endfor %}
        </div>
    </div>

        </div>
    </div>


    {% comment %} {% for a in id_number %}
        {{a}}
        {{a.id_number}}
    {% endfor %} {% endcomment %}

    
    

{% endblock contents %}